### ISSUE TITLE
Include event details for matches

### ISSUE THREAD

**Issue by MePsyDuck** [mdiller/twitchclipmatchfinder#5]
OpenDota API contains enough data to check if the  match was played in any event/league. We can include this info in the response, and if possible both teams as well.

Current:
`Looks like this is match 5208847252, which started 27 minutes before the clip was recorded.`

Expected:
`Looks like this is match 5208847252, Team Secret vs Fnatic from Dreamleague Season 13, which started 27 minutes before the clip was recorded.`

**Comment by mdiller** [comment]
Hmm interesting. When I read the title of this I thought you were going to ask for me to re-implement the other dota bot that gives you a table with match details, which my response to would have been that that bot already exists. But adding a little bit of extra flavor like this to give people a bit more context could be pretty interesting. I'll look into it, thanks!

**Comment by MePsyDuck** [comment]
If you don't mind, I would like to take care of this (unless you've already started working on it).

**Comment by mdiller** [comment]
Sure, sounds good to me! :)
