### ISSUE TITLE
Increasing accuracy using kill scores

### ISSUE THREAD

**Issue by hrishikeshrt** [mdiller/twitchclipmatchfinder#8]
How about checking the game time, and from opendota's match data, filtering out matches that match the kill score at the specific time? 
This can be done for multiple frames for longer clips/videos.
(I believe it's already pretty unlikely for two matches to have exact same draft that close to each other, but just an additional check since it would be further unlikely that they would have the same kill score at the same time stamp)

**Comment by mdiller** [comment]
Hey, first of all sorry for taking a while to respond to this issue, been on vacation and doin' other stuff that has gotten in the way of checking on my repositories.

While this would be possible to do, I'm happy with the current accuracy it has at the moment and think this would probably be overkill to implement. I've already got a thing that checks to find the match that has a start time closest to the clip creation date if there are multiple and I think that'll be sufficient. If I needed another factor to use though this would be a good one!
