### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by cye18** [mdiller/twitchclipmatchfinder#9]
Hi,

Thanks for the great work! It's really a genius idea to find the match id from a video. And it's one of the rare Dota2 projects that's still being developed. I really appreciate it.

I tried to run it locally and it returns an error saying `FileNotFoundError: [Errno 2] No such file or directory: 'config.json'`. I checked `finder.py` and saw it should be containing Twitch API token. I understand it's simple to read the code and figure out the structure of `config.json`, but just thought it could make more sense if a sample file is provided in the repo.

Thanks a lot.

**Comment by mdiller** [comment]
Thanks for the issue submit! I've updated the readme with some more info on this so it should be workable now.

Glad you appreciate the project :)
